[package]
name = "akikaze"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
futures_util = { workspace = true }
